version: '3'
services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: technical-test-troben
    container_name: technical-test-troben
    restart: always
    ports:
      - "1800:1800"
    volumes:
      - .:/app

volumes:
  cache:
    driver: local
